"""empty message

Revision ID: bdcaa3bf4158
Revises: 5efd4a277710
Create Date: 2023-07-10 16:36:06.893575

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdcaa3bf4158'
down_revision = '5efd4a277710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('brand', sa.String(), nullable=False))
        batch_op.drop_column('img')

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('img')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=False))

    with op.batch_alter_table('chart', schema=None) as batch_op:
        batch_op.add_column(sa.Column('img', sa.VARCHAR(), autoincrement=False, nullable=False))
        batch_op.drop_column('brand')

    # ### end Alembic commands ###
